import { Interaction } from '../models/interaction';

export const mock_meeting_bot_interactions: Interaction[] = [
  {
    slug: 'int-0a90e1da8c',
    interaction_type: 'message',
    message_type: 'text_message',
    interaction_text: 'Welcome to MeetingBot!',
    name: 'WelcomeMesssage',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: undefined,
    saving_to_both: true,
    is_welcome_interaction: true,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-E6482E6820',
    interaction_type: 'action',
    action_type: 'ask_consent',
    interaction_text: undefined,
    confirm_consent: true,
    name: '',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [
      {
        slug: 'INT-F2CF63890D',
        interaction_type: 'action',
        action_type: 'deny_consent',
        interaction_text: undefined,
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: undefined,
        contact_field_type: undefined,
        ask_if_exists: false,
        saving_to_both: false,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        email_alert_recipients: undefined,
      },
    ],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: 'has_consent',
    contact_field_type: 0,
    ask_if_exists: undefined,
    saving_to_both: true,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    email_alert_recipients: undefined,
  },
  {
    slug: 'int-6c0d92273d',
    interaction_type: 'action',
    action_type: 'schedule',
    interaction_text: 'Schedule a time',
    name: 'CO MBP',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [
      {
        slug: 'int-1612311914',
        interaction_type: 'message',
        message_type: 'text_message',
        interaction_text:
          'Thanks. Before we schedule your selected time, we need to get your details...',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: undefined,
        contact_field_type: undefined,
        ask_if_exists: undefined,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        email_alert_recipients: undefined,
      },
      {
        slug: 'int-797ee51d15',
        interaction_type: 'question',
        question_type: 'email',
        interaction_text: 'What is your email address?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'email',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'int-a48e0758de',
        interaction_type: 'question',
        question_type: 'text',
        interaction_text: 'What is your first name?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'first_name',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'int-a09dfdee03',
        interaction_type: 'question',
        question_type: 'text',
        interaction_text: 'What is your last name?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'last_name',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'int-2b8b31810f',
        interaction_type: 'question',
        question_type: 'phone',
        interaction_text: 'What is your mobile phone number?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'mobile_phone',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'int-2f16ddc412',
        interaction_type: 'question',
        question_type: 'time_zone',
        interaction_text:
          'Before offering available times to schedule please select your time zone',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'timezone',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
    ],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: undefined,
    saving_to_both: true,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    button_text: undefined,
    schedule_master_booking_page_id: undefined,
    schedule_event_type: 'NTQ4NzM%3d',
    schedule_additional_settings: false,
    schedule_ask_detail_message:
      'Thanks. Before we schedule your selected time, we need to get your details...',
    schedule_first_name: 'What is your first name?',
    schedule_last_name: 'What is your last name?',
    schedule_email: 'What is your email address?',
    schedule_fallback_message:
      'Oops… We are unable to schedule your meeting at this time. We will contact you by email.',
    schedule_timeslot_fallback_button_text: 'Select a new time',
    schedule_timeslot_fallback_message:
      'Oops… the time you selected has just been taken',
    schedule_panel_id: 'NzE2NQ%3d%3d',
    schedule_master_page_image: undefined,
    schedule_action_event_type_meeting_length: 30,
    schedule_action_time_zone_conversion: true,
    schedule_action_time_zone_conversion_prompt: false,
    schedule_action_booking_page_time_zone: 271,
    schedule_confirmation_title: 'Confirm your meeting details',
    schedule_sms_notification: false,
    schedule_mobile_phone_text: 'What is your mobile phone number?',
    schedule_sms_opt_in_text: 'OK to send me booking notifications via SMS',
    schedule_confirmation_button: 'Confirm',
    schedule_action_panel_members: [
      {
        ResourceId: 'MTEyMTUx',
        IsPrimary: true,
        ResourceType: 1,
        DisplayOrder: 0,
      },
      {
        ResourceId: 'ODEwNjM%3d',
        IsPrimary: false,
        ResourceType: 1,
        DisplayOrder: 1,
      },
      {
        ResourceId: 'MTAyNTM5',
        IsPrimary: false,
        ResourceType: 1,
        DisplayOrder: 2,
      },
    ],
    schedule_event_type_external_id: 'ET-8930PDFJZU',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-D1EFB7643F',
    interaction_type: 'question',
    question_type: 'multi_choice',
    interaction_text: 'New multi-select text question',
    name: 'text',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [
      {
        id: 471992,
        option_text: 'Test1',
        option_order: 1,
        jump_to_interaction_id: undefined,
        field_library_option_id: undefined,
        bot_response: '',
      },
      {
        id: 471993,
        option_text: 'Test2',
        option_order: 2,
        jump_to_interaction_id: undefined,
        field_library_option_id: undefined,
        bot_response: '',
      },
      {
        id: 471994,
        option_text: 'Test3',
        option_order: 3,
        jump_to_interaction_id: undefined,
        field_library_option_id: undefined,
        bot_response: '',
      },
      {
        id: 471995,
        option_text: 'Test4',
        option_order: 4,
        jump_to_interaction_id: undefined,
        field_library_option_id: undefined,
        bot_response: '',
      },
    ],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: 'list',
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: { slug: 'INT-8081530D44' },
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-3E39A6FA2D',
    interaction_type: 'question',
    question_type: 'time',
    interaction_text: 'Which time is suitable for you?',
    name: 'Time testing',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: '1 AM',
    time_end: '12 AM',
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: "Thanks, we'll adhere it!",
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-8081530D44',
    interaction_type: 'question',
    question_type: 'phone',
    interaction_text: 'Please share your mobile number',
    name: 'Test Phone',
    basic_route_slug: 'INT-4D4AC86EBB',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-E8EFD03B43',
    interaction_type: 'question',
    question_type: 'email',
    interaction_text: 'Please share your email.',
    name: 'Test email',
    basic_route_slug: 'INT-4D4AC86EBB',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: 'Great!',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-4D4AC86EBB',
    interaction_type: 'action',
    action_type: 'end_conversation',
    interaction_text: 'Thank you for joining!',
    name: 'endChat',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: undefined,
    saving_to_both: true,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    email_alert_recipients: undefined,
  },
];
