export interface Interaction {
  name?: string;
  slug?: string;
  question_type?: string;
  message_type?: string;
  action_type?: string;
  interaction_type: 'question' | 'message' | 'action';
  interaction_text?: string;
  selected?: boolean;
  errSelected?: boolean;
  scheduleSetupPending?: boolean;
  counter?: number;
  number_low?: number;
  number_high?: number;
  answer_character_limit?: number;
  time_start?: string;
  time_end?: string;
  require_in_future?: boolean;
  url?: string;
  title?: string;
  multi_choice_minimum?: number;
  multi_choice_maximum?: number;
  image?: string;
  document?: string;
  video?: string;
  interaction_options?: any[];
  multi_choice_type?: string;
  media_status?: string;
  file_key?: string;
  imageValue?: string;
  videoValue?: string;
  documentValue?: string;
  copiedStatus?: boolean;
  ask_consent_frequency?: string;
  saving_to_both?: boolean;
  contact_field_id?: string;
  contact_field_type?: number;
  ask_if_exists?: boolean;
  deleteMultiChoiceOptions?: boolean;
  schedule_ask_detail_message?: string;
  schedule_first_name?: string;
  schedule_last_name?: string;
  schedule_email?: string;
  schedule_fallback_message?: string;
  schedule_timeslot_fallback_message?: string;
  schedule_additional_settings?: boolean;
  schedule_timeslot_fallback_button_text?: string;
  schedule_action_event_type_meeting_length?: number;
  schedule_action_time_zone_conversion?: boolean;
  schedule_action_time_zone_conversion_prompt?: boolean;
  schedule_action_booking_page_time_zone?: number;
  button_text?: string;
  schedule_master_booking_page_id?: string;
  schedule_event_type?: string;
  schedule_event_type_external_id?: string;
  schedule_action_event_type?: string;
  schedule_panel_id?: string;
  schedule_master_page_image?: string;
  schedule_confirmation_title?: string;
  schedule_confirmation_button?: string;
  routingFullName?: string;
  is_welcome_interaction?: boolean;
  otherwise_route?: any;
  confirm_consent?: boolean;
  bot_response?: string;
  basic_route_slug?: string;
  label?: string;
  icon?: string;
  schedule_mobile_phone_text?: string;
  schedule_sms_opt_in_text?: string;
  schedule_sms_notification?: boolean;
  schedule_action_panel_members?: any;
  sub_title?: string;
  audio?: string;
  cards?: any[];
  jump_to_interaction?: any;
  match_send_type?: string;
  timeout_period?: number;
  handoff_message?: string;
  away_message?: string;
  email_alert_subject?: string;
  email_alert_message_body?: string;
  icon_type?: string;
  is_form_title?: boolean;
  show_form_title?: boolean;
  email_alert_recipients?: any[];
}

export const mock_interactions: Interaction[] = [
  {
    slug: 'INT-E4976CD373',
    interaction_type: 'question',
    question_type: 'text',
    interaction_text: 'Hi, How are you?',
    name: 'Welcome',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: 0,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: true,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: 'Great',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-E6476B244E',
    interaction_type: 'action',
    action_type: 'ask_consent',
    interaction_text: undefined,
    confirm_consent: true,
    name: '',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [
      {
        slug: 'INT-3A8D864CE4',
        interaction_type: 'action',
        action_type: 'deny_consent',
        interaction_text: undefined,
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: undefined,
        contact_field_type: undefined,
        ask_if_exists: false,
        saving_to_both: false,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        email_alert_recipients: undefined,
      },
    ],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: 'has_consent',
    contact_field_type: 0,
    ask_if_exists: undefined,
    saving_to_both: true,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-B94B393072',
    interaction_type: 'question',
    question_type: 'text',
    interaction_text: 'May I know your first name?',
    name: 'First Name',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: 0,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-CAAF75EDBB',
    interaction_type: 'question',
    question_type: 'text',
    interaction_text: 'And last name?',
    name: 'Last Name',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: 0,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: { slug: 'INT-0D971C7092' },
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-5642DF348A',
    interaction_type: 'question',
    question_type: 'text',
    interaction_text: 'What is your current city?',
    name: 'City',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: 0,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-84CF904410',
    interaction_type: 'question',
    question_type: 'text',
    interaction_text: 'We need your post code too',
    name: 'Post code',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: 0,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-0D971C7092',
    interaction_type: 'action',
    action_type: 'schedule',
    interaction_text: 'Please select a time and book a meeting',
    name: 'Select a time',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [
      {
        slug: 'INT-3A10CBBF81',
        interaction_type: 'message',
        message_type: 'text_message',
        interaction_text:
          'Thanks. Before we schedule your selected time, we need to get your details...',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: undefined,
        contact_field_type: undefined,
        ask_if_exists: undefined,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        email_alert_recipients: undefined,
      },
      {
        slug: 'INT-5E1A75B213',
        interaction_type: 'question',
        question_type: 'email',
        interaction_text: 'What is your email address?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'email',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'INT-60472C55F6',
        interaction_type: 'question',
        question_type: 'text',
        interaction_text: 'What is your first name?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'first_name',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'INT-74BC047585',
        interaction_type: 'question',
        question_type: 'text',
        interaction_text: 'What is your last name?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'last_name',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'INT-ABEFD9C5CF',
        interaction_type: 'question',
        question_type: 'phone',
        interaction_text: 'What is your mobile phone number?',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'mobile_phone',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
      {
        slug: 'INT-496F36AB8A',
        interaction_type: 'question',
        question_type: 'time_zone',
        interaction_text:
          'Before offering available times to schedule please select your time zone',
        name: '',
        basic_route_slug: '',
        title: undefined,
        sub_title: undefined,
        image: undefined,
        audio: undefined,
        video: undefined,
        document: undefined,
        cards: [],
        jump_to_interaction: undefined,
        number_low: undefined,
        number_high: undefined,
        multi_choice_minimum: undefined,
        multi_choice_maximum: undefined,
        match_send_type: undefined,
        interaction_options: [],
        require_in_future: false,
        time_start: undefined,
        time_end: undefined,
        answer_character_limit: undefined,
        url: undefined,
        multi_choice_type: undefined,
        media_status: 'processing',
        contact_field_id: 'timezone',
        contact_field_type: undefined,
        ask_if_exists: true,
        saving_to_both: true,
        is_welcome_interaction: false,
        otherwise_route: undefined,
        ask_consent_frequency: 'ask_once',
        bot_response: '',
        email_alert_recipients: undefined,
      },
    ],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: undefined,
    saving_to_both: true,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    button_text: undefined,
    schedule_master_booking_page_id: undefined,
    schedule_event_type: 'NTc1OTg%3d',
    schedule_additional_settings: false,
    schedule_ask_detail_message:
      'Thanks. Before we schedule your selected time, we need to get your details...',
    schedule_first_name: 'What is your first name?',
    schedule_last_name: 'What is your last name?',
    schedule_email: 'What is your email address?',
    schedule_fallback_message:
      'Oops… We are unable to schedule your meeting at this time. We will contact you by email.',
    schedule_timeslot_fallback_button_text: 'Select a new time',
    schedule_timeslot_fallback_message:
      'Oops… the time you selected has just been taken',
    schedule_panel_id: 'Mjg5Nzk%3d',
    schedule_master_page_image: undefined,
    schedule_action_event_type_meeting_length: 30,
    schedule_action_time_zone_conversion: true,
    schedule_action_time_zone_conversion_prompt: false,
    schedule_action_booking_page_time_zone: 122,
    schedule_confirmation_title: 'Confirm your meeting details',
    schedule_sms_notification: false,
    schedule_mobile_phone_text: 'What is your mobile phone number?',
    schedule_sms_opt_in_text: 'OK to send me booking notifications via SMS',
    schedule_confirmation_button: 'Confirm',
    schedule_action_panel_members: [
      {
        ResourceId: 'ODIyMTM%3d',
        IsPrimary: true,
        ResourceType: 1,
        DisplayOrder: 0,
      },
    ],
    schedule_event_type_external_id: 'ET-ZX408Y5SMR',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-93ECA1238E',
    interaction_type: 'question',
    question_type: 'text',
    interaction_text: 'For what reason you want this meeting?',
    name: 'Meeting agenda',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: 1,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-D211D9EBCE',
    interaction_type: 'question',
    question_type: 'multi_choice',
    interaction_text: 'Please pick your choices',
    name: 'Choose something',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [
      {
        id: 472004,
        option_text: 'Third',
        option_order: 1,
        jump_to_interaction_id: undefined,
        field_library_option_id: undefined,
        bot_response: '',
      },
      {
        id: 472005,
        option_text: 'First',
        option_order: 2,
        jump_to_interaction_id: undefined,
        field_library_option_id: undefined,
        bot_response: '',
      },
      {
        id: 472006,
        option_text: 'Second',
        option_order: 3,
        jump_to_interaction_id: undefined,
        field_library_option_id: undefined,
        bot_response: '',
      },
    ],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: 'list',
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: false,
    saving_to_both: false,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    bot_response: '',
    email_alert_recipients: undefined,
  },
  {
    slug: 'INT-89B531AADE',
    interaction_type: 'action',
    action_type: 'end_conversation',
    interaction_text: 'Thank you so much, have a great day!!!',
    name: 'End',
    basic_route_slug: '',
    title: undefined,
    sub_title: undefined,
    image: undefined,
    audio: undefined,
    video: undefined,
    document: undefined,
    cards: [],
    jump_to_interaction: undefined,
    number_low: undefined,
    number_high: undefined,
    multi_choice_minimum: undefined,
    multi_choice_maximum: undefined,
    match_send_type: undefined,
    interaction_options: [],
    require_in_future: false,
    time_start: undefined,
    time_end: undefined,
    answer_character_limit: undefined,
    url: undefined,
    multi_choice_type: undefined,
    media_status: 'processing',
    contact_field_id: undefined,
    contact_field_type: undefined,
    ask_if_exists: undefined,
    saving_to_both: true,
    is_welcome_interaction: false,
    otherwise_route: undefined,
    ask_consent_frequency: 'ask_once',
    email_alert_recipients: undefined,
  },
];
